### ISSUE TITLE
Add page for API to documentation

### ISSUE THREAD

**Issue by oskooi** [NanoComp/imageruler#31] opened 2024-03-28 19:19 UTC
The [documentation](https://mfschubert.github.io/imageruler/readme.html) which is based on Sphinx is missing a page which lists all the main functions available from the API. This page can be created automatically from the docstrings.

**Comment by stevengj** [comment] 2024-03-28 19:24
Duplicate of #1?

**Closed** 2024-03-28 19:24 UTC
Labels: documentation
